[package]
name = "glyph_fun"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
owned_ttf_parser = "0.8.0"
harfbuzz_rs = "1.2.0"
anyhow = "1"
wgpu_launchpad = { path = "../wgpu_launchpad" }
bytemuck = "1.4"
lyon = "0.16"
